from pathlib import Path
import sys

path=Path(sys.argv[1] if len(sys.argv)>1 else 'app.py')
text=path.read_text(encoding='utf-8')

old_metrics="            ec1,ec2,ec3,ec4=st.columns(4)\n            ec1.metric('Episode 수',len(e))\n            ec2.metric('60분 완료',int(e['ret_60m'].notna().sum()) if 'ret_60m' in e.columns else 0)\n            ec3.metric('READY 이상',int(e['max_state'].isin(['READY','ENTRY','HOLD','PARTIAL_EXIT','EXIT_READY','HARD_EXIT']).sum()) if 'max_state' in e.columns else 0)\n            ec4.metric('ENTRY 도달',int(e['max_state'].isin(['ENTRY','HOLD','PARTIAL_EXIT','EXIT_READY','HARD_EXIT']).sum()) if 'max_state' in e.columns else 0)\n"
new_metrics="            # V4.5.2: count only states that were actually observed in marks.\n            # Do not infer ENTRY from downstream position/exit states.\n            reach_anchors=api(f'/api/v4/validation/stage-anchors?market={m}&limit=5000&bridge_minutes=5').get('data') or []\n            reach_df=pd.DataFrame(reach_anchors) if reach_anchors else pd.DataFrame()\n            if len(reach_df):\n                reach_df['stage_dt']=pd.to_datetime(reach_df['stage_ts'],utc=True,errors='coerce')\n                if m=='USA':\n                    try:reach_df['reach_date']=reach_df['stage_dt'].dt.tz_convert('America/New_York').dt.date.astype(str)\n                    except Exception:reach_df['reach_date']=reach_df['stage_dt'].dt.date.astype(str)\n                else:\n                    try:reach_df['reach_date']=reach_df['stage_dt'].dt.tz_convert('Asia/Seoul').dt.date.astype(str)\n                    except Exception:reach_df['reach_date']=reach_df['stage_dt'].dt.date.astype(str)\n                reach_day=reach_df[reach_df['reach_date']==report_date].copy() if report_date else reach_df.copy()\n            else:\n                reach_day=pd.DataFrame()\n\n            observed_ready=int((reach_day['stage']=='READY').sum()) if len(reach_day) and 'stage' in reach_day.columns else 0\n            observed_entry=int((reach_day['stage']=='ENTRY').sum()) if len(reach_day) and 'stage' in reach_day.columns else 0\n\n            ec1,ec2,ec3,ec4=st.columns(4)\n            ec1.metric('Episode 수',len(e))\n            ec2.metric('60분 완료',int(e['ret_60m'].notna().sum()) if 'ret_60m' in e.columns else 0)\n            ec3.metric('READY 실제 관측',observed_ready)\n            ec4.metric('ENTRY 실제 관측',observed_entry)\n"
stage_anchor="                st.markdown('##### SETUP vs READY vs ENTRY')\n                st.dataframe(pd.DataFrame(summary),use_container_width=True,hide_index=True)\n\n                ready=a[a['stage']=='READY'].copy()\n"
stage_insert="                st.markdown('##### SETUP vs READY vs ENTRY')\n                st.dataframe(pd.DataFrame(summary),use_container_width=True,hide_index=True)\n\n                # V4.5.2 Stage Funnel: actual observed reach semantics.\n                setup_ids=set(a.loc[a['stage']=='SETUP','episode_id'].dropna().astype(int).tolist()) if 'episode_id' in a.columns else set()\n                ready_ids=set(a.loc[a['stage']=='READY','episode_id'].dropna().astype(int).tolist()) if 'episode_id' in a.columns else set()\n                entry_ids=set(a.loc[a['stage']=='ENTRY','episode_id'].dropna().astype(int).tolist()) if 'episode_id' in a.columns else set()\n\n                total_eps=len(e) if 'e' in locals() else len(setup_ids | ready_ids | entry_ids)\n                setup_reach=len(setup_ids)\n                ready_reach=len(ready_ids)\n                entry_reach=len(entry_ids)\n\n                st.markdown('##### 🪜 실제 관측 Stage Funnel')\n                f1,f2,f3,f4=st.columns(4)\n                f1.metric('Episode',total_eps)\n                f2.metric('SETUP 관측',setup_reach)\n                f3.metric('READY 관측',ready_reach)\n                f4.metric('ENTRY 관측',entry_reach)\n\n                ready_rate=(ready_reach/setup_reach*100) if setup_reach else 0.0\n                entry_from_ready=(entry_reach/ready_reach*100) if ready_reach else 0.0\n                entry_from_setup=(entry_reach/setup_reach*100) if setup_reach else 0.0\n\n                q1,q2,q3=st.columns(3)\n                q1.metric('SETUP → READY',f'{ready_rate:.1f}%')\n                q2.metric('READY → ENTRY',f'{entry_from_ready:.1f}%')\n                q3.metric('SETUP → ENTRY',f'{entry_from_setup:.1f}%')\n\n                # Average delay is calculated only from actually observed anchors.\n                ready_delay=a.loc[a['stage']=='READY','minutes_from_episode_start'].dropna()\n                entry_delay=a.loc[a['stage']=='ENTRY','minutes_from_episode_start'].dropna()\n                d1,d2=st.columns(2)\n                d1.metric('READY 평균 도달시간',f'{ready_delay.mean():.1f}분' if len(ready_delay) else '-')\n                d2.metric('ENTRY 평균 도달시간',f'{entry_delay.mean():.1f}분' if len(entry_delay) else '-')\n\n                if entry_reach==0:\n                    st.info('오늘 데이터에는 실제 ENTRY 상태가 관측되지 않았습니다. HOLD/EXIT 계열 상태가 있더라도 ENTRY 도달로 추정하지 않습니다.')\n                elif entry_reach<5:\n                    st.warning(f'ENTRY 실제 관측은 {entry_reach}건뿐입니다. 진입 임계값 보정에는 아직 표본이 부족합니다.')\n\n                ready=a[a['stage']=='READY'].copy()\n"
footer_old="st.caption('V4.5.1 · STAGE-ANCHOR + EPISODE VALIDATION · MAX 5 HEAVY TRACKING · MANUAL ORDER ONLY')"
footer_new="st.caption('V4.5.2 · STAGE FUNNEL + OBSERVED REACH SEMANTICS · MAX 5 HEAVY TRACKING · MANUAL ORDER ONLY')"

if 'READY 실제 관측' in text and '실제 관측 Stage Funnel' in text:
    raise SystemExit('PATCH ABORTED: V4.5.2 already present; app.py unchanged.')
if old_metrics not in text:
    raise SystemExit('PATCH ABORTED: Episode metric block not found; app.py unchanged.')
if stage_anchor not in text:
    raise SystemExit('PATCH ABORTED: Stage-Anchor insertion point not found; app.py unchanged.')

text=text.replace(old_metrics,new_metrics,1)
text=text.replace(stage_anchor,stage_insert,1)
if footer_old in text:
    text=text.replace(footer_old,footer_new,1)

path.write_text(text,encoding='utf-8')
print('PATCHED:',path)
