from pathlib import Path
import sys
root=Path(sys.argv[1] if len(sys.argv)>1 else '.')
engine_path=root/'live_server'/'v4_engine.py'
api_path=root/'live_server'/'api.py'
app_path=root/'app.py'
engine=engine_path.read_text(encoding='utf-8')
api=api_path.read_text(encoding='utf-8')
app=app_path.read_text(encoding='utf-8')

if 'shadow_min_recent_bars=0' in engine:
    raise SystemExit('PATCH ABORTED: V4.6.2.1 engine already present; no files changed.')
if 'warm_bridge_candidates' in api:
    raise SystemExit('PATCH ABORTED: V4.6.2.1 API already present; no files changed.')
if '핵심 Leveraged / Inverse ETF 데이터 준비' in app:
    raise SystemExit('PATCH ABORTED: V4.6.2.1 UI already present; no files changed.')

for old,new in [
('    def build_usa_finder(self,candidates,discovery,limit=5,db=None,commit=True,shadow_allow_unknown_quality=False):\n','    def build_usa_finder(self,candidates,discovery,limit=5,db=None,commit=True,shadow_allow_unknown_quality=False,shadow_min_recent_bars=0):\n'),
("        heavy_pool=[\n            r for r in light_rows\n            if r.get('quality')!='C_HIGH_RISK' or r.get('extreme_continue')\n        ]\n        selected=heavy_pool[:limit]\n","        heavy_pool=[\n            r for r in light_rows\n            if r.get('quality')!='C_HIGH_RISK' or r.get('extreme_continue')\n        ]\n        # V4.6.2.1 fair-comparison guard:\n        # unknown-quality Bridge rows may appear in Light diagnostics immediately,\n        # but cannot enter Shadow Finder until enough 1m bars exist.\n        if not commit and int(shadow_min_recent_bars or 0)>0:\n            heavy_pool=[\n                r for r in heavy_pool\n                if (not r.get('shadow_quality_unknown'))\n                or int(r.get('recent_bars') or 0)>=int(shadow_min_recent_bars)\n            ]\n        selected=heavy_pool[:limit]\n"),
]:
    if old not in engine: raise SystemExit('PATCH ABORTED: engine anchor missing; no files changed.')
    engine=engine.replace(old,new,1)

for old,new in [
("async def v4_engine_forever():\n    last={'USA':0.0,'KOREA':0.0}\n    warmed_usa=set()\n","async def v4_engine_forever():\n    last={'USA':0.0,'KOREA':0.0}\n    warmed_usa=set()\n    bridge_warmed=set()\n    bridge_warm_task=None\n"),
('        warmed_usa.update(new_syms)\n\n    while True:\n',"        warmed_usa.update(new_syms)\n\n    async def warm_bridge_candidates(candidates,discovery):\n        # V4.6.2.1: prepare data only. This does NOT add symbols to live Finder.\n        # Warm the highest Screener-eligible names absent from Discovery plus\n        # the core leveraged/inverse ETFs whose data must always be auditable.\n        nonlocal bridge_warmed\n        d=discovery if isinstance(discovery,dict) else {}\n        seen=set()\n        for key in ('rows','extreme_rows','quality_risk_rows'):\n            seen.update(\n                str(r.get('symbol') or '').upper()\n                for r in (d.get(key) or []) if r.get('symbol')\n            )\n\n        misses=[\n            r for r in (candidates or [])\n            if r.get('eligible')\n            and str(r.get('symbol') or '').upper()\n            and str(r.get('symbol') or '').upper() not in seen\n        ]\n        misses.sort(\n            key=lambda r:(float(r.get('score') or 0),abs(float(r.get('change_pct') or 0))),\n            reverse=True\n        )\n\n        wanted=[]\n        for r in misses[:8]:\n            sym=str(r.get('symbol') or '').upper()\n            if sym and sym not in wanted:wanted.append(sym)\n        for sym in ('SOXS','SQQQ','SOXL','TQQQ'):\n            if sym not in wanted:wanted.append(sym)\n\n        new_syms=[x for x in wanted if x not in bridge_warmed]\n        if not new_syms:return\n\n        for sym in new_syms[:12]:\n            try:\n                ex=k.active_exchange(sym)\n                await asyncio.to_thread(k.quote,sym,ex)\n                await asyncio.to_thread(k.daily_metrics,sym,ex)\n                inserted,bars=await asyncio.to_thread(k.backfill_symbol,sym,ex,80)\n                bridge_warmed.add(sym)\n                logging.info(\n                    'V4 bridge warmup %s/%s: bars=%s inserted=%s',\n                    sym,ex,bars,inserted\n                )\n            except Exception as e:\n                # Do not mark failed symbols as warmed; retry on a later cycle.\n                logging.warning('V4 bridge warmup %s failed: %s',sym,e)\n            await asyncio.sleep(0.12)\n\n    while True:\n"),
("            if now-last['USA']>=30:\n                finder=v4.build_usa_finder(\n                    screener_rows(db.quotes(),db.daily_metrics(),40),\n                    k.discovery,5,db=db\n                )\n                finder_syms=[r.get('symbol') for r in (finder.get('rows') or [])]\n","            if now-last['USA']>=30:\n                usa_candidates=screener_rows(db.quotes(),db.daily_metrics(),40)\n                finder=v4.build_usa_finder(\n                    usa_candidates,\n                    k.discovery,5,db=db\n                )\n                # Candidate data warming runs asynchronously so live Finder/Tracker\n                # is never blocked by extra quote/daily/minute requests.\n                if bridge_warm_task is None or bridge_warm_task.done():\n                    bridge_warm_task=asyncio.create_task(\n                        warm_bridge_candidates(usa_candidates,k.discovery)\n                    )\n                finder_syms=[r.get('symbol') for r in (finder.get('rows') or [])]\n"),
('    shadow=v4.build_usa_finder(\n        candidates,discovery,5,db=db,\n        commit=False,shadow_allow_unknown_quality=True\n    )\n','    shadow=v4.build_usa_finder(\n        candidates,discovery,5,db=db,\n        commit=False,shadow_allow_unknown_quality=True,\n        shadow_min_recent_bars=6\n    )\n'),
("        srow=sh_l.get(sym) or sh_f.get(sym)\n        misses.append({\n            'symbol':sym,\n","        srow=sh_l.get(sym) or sh_f.get(sym)\n        recent_bars=int((srow or {}).get('recent_bars') or 0)\n        price=float((srow or {}).get('price') or (db.quote(sym) or {}).get('price') or 0)\n        data_ready=bool(recent_bars>=6 and price>0)\n        misses.append({\n            'symbol':sym,\n"),
("            'shadow_quality':(srow or {}).get('quality'),\n            'recent_bars':(srow or {}).get('recent_bars'),\n            'fresh':(srow or {}).get('fresh_mode'),\n","            'shadow_quality':(srow or {}).get('quality'),\n            'price':price,\n            'recent_bars':recent_bars,\n            'data_ready':data_ready,\n            'fair_status':'READY' if data_ready else 'INSUFFICIENT_DATA',\n            'fresh':(srow or {}).get('fresh_mode'),\n"),
("            'would_reach_light':sym in sh_l,\n            'would_reach_finder':sym in sh_f,\n            'note':(\n                'Finder Shadow TOP5' if sym in sh_f else\n                'Light Shadow only' if sym in sh_l else\n                'Shadow에서도 Light20 미진입'\n            )\n","            'would_reach_light':sym in sh_l,\n            'would_reach_finder':sym in sh_f,\n            'note':(\n                'Finder Shadow TOP5 · fair data ready' if sym in sh_f else\n                'Light Shadow only · fair data ready' if sym in sh_l and data_ready else\n                'Light에는 보이나 데이터 준비 부족' if sym in sh_l else\n                'Shadow에서도 Light20 미진입'\n            )\n"),
("        'shadow_light_count':len(shadow_light),\n        'unknown_quality_policy':'Screener eligible + missing verified discovery quality => SHADOW_UNKNOWN, quality bonus 0',\n        'note':'Shadow only. Same Finder scoring path, commit=False. No live Finder state/event/order is changed.'\n    }\n","        'shadow_light_count':len(shadow_light),\n        'data_ready_misses':sum(1 for r in misses if r.get('data_ready')),\n        'insufficient_data_misses':sum(1 for r in misses if not r.get('data_ready')),\n        'core_etf_readiness':[\n            {\n                'symbol':sym,\n                'price':float((db.quote(sym) or {}).get('price') or 0),\n                'minute_bars':len(ticks_to_bars(db.ticks(sym,2500),1)),\n                'ready':bool(\n                    float((db.quote(sym) or {}).get('price') or 0)>0\n                    and len(ticks_to_bars(db.ticks(sym,2500),1))>=6\n                )\n            }\n            for sym in ('SOXS','SQQQ','SOXL','TQQQ')\n        ],\n        'fair_guard':'SHADOW_UNKNOWN requires recent_bars >= 6 before Shadow Finder eligibility',\n        'unknown_quality_policy':'Screener eligible + missing verified discovery quality => SHADOW_UNKNOWN, quality bonus 0',\n        'note':'Shadow only. Candidate data is warmed separately; live Finder state/event/order is unchanged.'\n    }\n"),
]:
    if old not in api: raise SystemExit('PATCH ABORTED: api anchor missing; no files changed.')
    api=api.replace(old,new,1)

for old,new in [
("                b1,b2,b3=st.columns(3)\n                b1.metric('가상 Finder 신규',len(bridge.get('new_shadow_entrants') or []))\n                b2.metric('가상으로 밀려난 기존',len(bridge.get('displaced_live') or []))\n                b3.metric('Shadow Light',bridge.get('shadow_light_count',0))\n","                b1,b2,b3,b4=st.columns(4)\n                b1.metric('가상 Finder 신규',len(bridge.get('new_shadow_entrants') or []))\n                b2.metric('가상으로 밀려난 기존',len(bridge.get('displaced_live') or []))\n                b3.metric('데이터 준비 Miss',bridge.get('data_ready_misses',0))\n                b4.metric('준비 부족 Miss',bridge.get('insufficient_data_misses',0))\n"),
("                        'shadow_light_rank','shadow_finder_rank','shadow_finder_score',\n                        'shadow_quality','recent_bars','fresh','fresh_score',\n","                        'shadow_light_rank','shadow_finder_rank','shadow_finder_score',\n                        'shadow_quality','price','recent_bars','data_ready','fair_status','fresh','fresh_score',\n"),
("                st.caption('주의: 이 Shadow는 품질정보 누락 종목에 Quality 보너스를 주지 않습니다. minute bars가 부족하면 recent/Fresh가 0에 가깝게 평가될 수 있으므로 recent_bars도 함께 봐야 합니다.')\n","                etf=pd.DataFrame(bridge.get('core_etf_readiness') or [])\n                if len(etf):\n                    st.markdown('###### 핵심 Leveraged / Inverse ETF 데이터 준비')\n                    st.dataframe(etf,use_container_width=True,hide_index=True)\n                st.caption('Fair Guard: SHADOW_UNKNOWN은 recent_bars≥6 + price>0일 때만 Shadow Finder에 들어갈 수 있습니다. 품질정보 누락 종목에는 Quality 보너스를 주지 않습니다.')\n"),
]:
    if old not in app: raise SystemExit('PATCH ABORTED: app anchor missing; no files changed.')
    app=app.replace(old,new,1)

if "st.caption('V4.6.2 · DISCOVERY BRIDGE SHADOW AUDIT · MAX 5 HEAVY TRACKING · MANUAL ORDER ONLY')" in app: app=app.replace("st.caption('V4.6.2 · DISCOVERY BRIDGE SHADOW AUDIT · MAX 5 HEAVY TRACKING · MANUAL ORDER ONLY')","st.caption('V4.6.2.1 · CANDIDATE DATA WARM + FAIR BRIDGE AUDIT · MAX 5 HEAVY TRACKING · MANUAL ORDER ONLY')",1)

engine_path.write_text(engine,encoding='utf-8')
api_path.write_text(api,encoding='utf-8')
app_path.write_text(app,encoding='utf-8')
print('PATCHED:',engine_path)
print('PATCHED:',api_path)
print('PATCHED:',app_path)
