from pathlib import Path

p=Path('live_server/v4_engine.py')
s=p.read_text()
old='''        if getattr(self, "_williams_mock_account_synced", False):\n            cash_bal = broker.request_account(\n                "kt00001",\n                {"qry_tp":"2"},\n            )\n            bal = dict(getattr(self, '_williams_mock_account_cache', {}) or {})\n            if isinstance(cash_bal, dict):\n                bal.update(cash_bal)\n            self._williams_mock_account_cache = bal\n            self._williams_mock_account_cache_mono = _time.monotonic()\n            return\n'''
new='''        if getattr(self, "_williams_mock_account_synced", False):\n            cash_bal = broker.request_account(\n                "kt00001",\n                {"qry_tp":"2"},\n            )\n            pos_bal = broker.request_account(\n                "kt00004",\n                {"qry_tp":"0", "dmst_stex_tp":"KRX"},\n            )\n            bal = dict(pos_bal or getattr(self, '_williams_mock_account_cache', {}) or {})\n            if isinstance(cash_bal, dict):\n                bal.update(cash_bal)\n            self._williams_mock_account_cache = bal\n            self._williams_mock_account_cache_mono = _time.monotonic()\n\n            from datetime import datetime as _dt\n            now = _dt.now(_WILLIAMS_KST)\n            live_syms=set()\n            for x in (pos_bal.get("stk_acnt_evlt_prst", []) or []) if isinstance(pos_bal, dict) else []:\n                sym = str(x.get("stk_cd") or "").replace("A", "").zfill(6)\n                try:\n                    qty = int(str(x.get("rmnd_qty") or "0").replace(",", ""))\n                except Exception:\n                    qty = 0\n                if not sym or qty <= 0:\n                    continue\n                try:\n                    avg = float(str(x.get("avg_prc") or "0").replace(",", ""))\n                except Exception:\n                    avg = 0.0\n                live_syms.add(sym)\n                key=("WILLIAMS_MOCK", sym)\n                st=dict(self._last.get(key) or {})\n                st["in_pos"]=True\n                st["qty"]=qty\n                if avg>0:\n                    st["entry_price"]=avg\n                st.setdefault("entered_ts", 0.0)\n                st.setdefault("entered_bar_time", now.strftime('%Y%m%d%H%M%S'))\n                st["synced_from_account"]=True\n                self._last[key]=st\n\n            for key,st in list(self._last.items()):\n                if not (isinstance(key, tuple) and len(key)==2 and key[0]=="WILLIAMS_MOCK"):\n                    continue\n                sym=str(key[1]).zfill(6)\n                if isinstance(st, dict) and st.get("in_pos") and st.get("synced_from_account") and sym not in live_syms:\n                    st=dict(st)\n                    st["in_pos"]=False\n                    st["qty"]=0\n                    self._last[key]=st\n\n            import logging as _logging\n            _logging.warning("WILLIAMS_MOCK_ACCOUNT_RESYNC open_positions=%s symbols=%s",len(live_syms),sorted(live_syms))\n            return\n'''
if new in s:
    print('V23 KR POSITION RESYNC ALREADY CONNECTED')
elif old not in s:
    raise SystemExit('EXACT RESYNC BLOCK NOT FOUND - NOTHING CHANGED')
else:
    s=s.replace(old,new,1)
    p.write_text(s)
    print('V23 KR POSITION RESYNC CONNECTED')
